const actionTypes = {
  SPOTIFY_AUTH: 'SPOTIFY_AUTH',
  SEARCH_PAYLOAD: 'SEARCH_PAYLOAD',
  SEARCH_ERROR: 'SEARCH_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGGED_IN: 'LOGGED_IN',
  FETCH_USER: 'FETCH_USER',
  NEW_PLAYLIST_INFO: 'NEW_PLAYLIST_INFO',
  FETCH_USER_PLAYLISTS: 'FETCH_USER_PLAYLISTS'
};

export default actionTypes;
