const actionTypes = {
  SPOTIFY_AUTH: 'SPOTIFY_AUTH',
  SEARCH_PAYLOAD: 'SEARCH_PAYLOAD',
  SEARCH_ERROR: 'SEARCH_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGGED_IN: 'LOGGED_IN',
  PLAYLIST_INFO: 'PLAYLIST_INFO',
  FETCH_USER: 'FETCH_USER'
};

export default actionTypes;
